[project]
name = "bwpy"
version = "0.1.0"
description = "bitwarden cli"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=44.0.1",
    "pyotp>=2.9.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
]

[project.scripts]
bwpy = "bwpy:main"
